services:
  web:
    environment:
      - NODE_ENV=development
      - TEST_MODE=1
      - NEXT_PUBLIC_TEST_MODE=1
      - CSRF_DOUBLE_SUBMIT=0
      - FEATURES_EXPERTFOLIO=1
      - NEXT_PUBLIC_SUPABASE_URL=https://ukeqjiattiaokdqjqncf.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrZXFqaWF0dGlhb2tkcWpxbmNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTI3NzIsImV4cCI6MjA3MDY2ODc3Mn0.sYYDUgwCt4X4k9ME6a_G2R3BA6GftI3WAcWVqBv2h2E
      - E2E_ALLOW_TEST_MODE=1
