name: E2E Full

on:
  push:
    branches: ['main']
  workflow_dispatch: {}

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: ["1/3", "2/3", "3/3"]
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Concurrency (cancel in-progress)
        uses: softprops/turnstyle@v1
        with:
          abort-after-seconds: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        working-directory: tests
        run: npx playwright install --with-deps

      - name: Run full Playwright suite (sharded)
        env:
          PW_WORKERS: '1'
          CI: 'true'
        working-directory: tests
        run: npx playwright test -c ./e2e/playwright.config.ts --shard=${{ matrix.shard }}

      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-full
          path: |
            tests/playwright-report
            tests/test-results
          if-no-files-found: ignore


