name: Nightly Synthetic Smoke

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      baseUrl:
        description: 'Base URL to test (defaults to PROD_BASE_URL secret)'
        required: false

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_BASE_URL: ${{ github.event.inputs.baseUrl || secrets.PROD_BASE_URL }}
      PW_NO_SERVER: 1
      PW_WORKERS: 1
      PLAYWRIGHT_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      PLAYWRIGHT_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      PLAYWRIGHT_LOGIN_EMAIL: ${{ secrets.E2E_LOGIN_EMAIL || 'admin@expertcollege.com' }}
      PLAYWRIGHT_LOGIN_PASSWORD: ${{ secrets.E2E_LOGIN_PASSWORD || 'TempPass!234' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright @smoke subset
        run: npx playwright test -c tests/e2e/playwright.config.ts -g @smoke

      - name: Upload smoke artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nightly-smoke-results
          path: tests/test-results/**
          if-no-files-found: warn


