name: Synthetic EF Smoke

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  ef-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build web image
        run: |
          docker compose build web

      - name: Start web (TEST_MODE via override)
        env:
          WEB_PORT: 3022
        run: |
          docker compose up -d web

      - name: Wait for health
        run: |
          for i in {1..30}; do curl -fsS http://localhost:3022/api/ready && exit 0; sleep 2; done; exit 1

      - name: EF smoke - POST assessment
        id: post_assessment
        run: |
          BODY='{"programId":"11111111-1111-1111-1111-111111111111","epaId":"22222222-2222-2222-2222-222222222222"}'
          RES=$(curl -s -i -X POST http://localhost:3022/api/ef/assessments \
            -H 'Content-Type: application/json' \
            -H 'x-test-auth: teacher' \
            -H 'origin: http://localhost:3022' \
            -H 'referer: http://localhost:3022/x' \
            --data "$BODY")
          echo "$RES" > ef-post-assessment.txt
          STATUS=$(printf "%s" "$RES" | awk 'NR==1{print $2}')
          echo "status=$STATUS" >> $GITHUB_OUTPUT
          test "$STATUS" = "201"

      - name: EF smoke - POST evaluation (optional)
        if: always()
        run: |
          BODY='{"assessmentId":"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa","outcome":"approved"}'
          curl -s -i -X POST http://localhost:3022/api/ef/evaluations \
            -H 'Content-Type: application/json' \
            -H 'x-test-auth: teacher' \
            -H 'origin: http://localhost:3022' \
            -H 'referer: http://localhost:3022/x' \
            --data "$BODY" > ef-post-evaluation.txt || true

      - name: Upload smoke artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ef-smoke
          path: |
            ef-post-assessment.txt
            ef-post-evaluation.txt

      - name: Compose down
        if: always()
        run: |
          docker compose down -v || true


